// Copyright 2026, the gaby-vm authors
// SPDX-License-Identifier: BSD-3-Clause
#include "fixture_writer.h"

#include <cctype>
#include <cstdio>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <utility>

namespace gaby_vm::extract {
namespace {

const char* KindName(AssertKind k) {
  switch (k) {
    case AssertKind::kX:
      return "AssertKind::kX";
    case AssertKind::kW:
      return "AssertKind::kW";
    case AssertKind::kNZCV:
      return "AssertKind::kNZCV";
    case AssertKind::kFP32:
      return "AssertKind::kFP32";
    case AssertKind::kFP64:
      return "AssertKind::kFP64";
    case AssertKind::kV128:
      return "AssertKind::kV128";
  }
  return "AssertKind::kX";
}

std::string Hex(uint64_t v) {
  std::ostringstream os;
  os << "0x" << std::hex << v << "ull";
  return os.str();
}

bool EntryEqual(const EntryState& a, const EntryState& b) {
  for (int i = 0; i < 31; ++i) {
    if (a.x[i] != b.x[i]) {
      return false;
    }
  }
  if (a.sp != b.sp) {
    return false;
  }
  for (int i = 0; i < 32; ++i) {
    if (a.v_lo[i] != b.v_lo[i] || a.v_hi[i] != b.v_hi[i]) {
      return false;
    }
  }
  return a.nzcv == b.nzcv && a.fpcr == b.fpcr && a.fpsr == b.fpsr;
}

// Emit the body of a RegisterFile factory: an `rf{}` value-init plus one
// assignment per non-zero field. sp / x[30] are intentionally never emitted
// (the replay runner overrides them).
void EmitEntryBody(std::ostream& os, const EntryState& e) {
  os << "  RegisterFile rf{};\n";
  for (int i = 0; i < 30; ++i) {
    if (e.x[i]) {
      os << "  rf.x[" << i << "] = " << Hex(e.x[i]) << ";\n";
    }
  }
  for (int i = 0; i < 32; ++i) {
    if (e.v_lo[i] || e.v_hi[i]) {
      os << "  rf.v[" << i << "] = {" << Hex(e.v_lo[i]) << ", "
         << Hex(e.v_hi[i]) << "};\n";
    }
  }
  if (e.nzcv) {
    os << "  rf.nzcv = " << Hex(e.nzcv) << ";\n";
  }
  if (e.fpcr) {
    os << "  rf.fpcr = " << Hex(e.fpcr) << ";\n";
  }
  if (e.fpsr) {
    os << "  rf.fpsr = " << Hex(e.fpsr) << ";\n";
  }
  os << "  return rf;\n";
}

std::string Lower(const std::string& s) {
  std::string r = s;
  for (char& c : r) {
    c = static_cast<char>(std::tolower((unsigned char)c));
  }
  return r;
}

}  // namespace

FixtureWriter::FixtureWriter(std::string inc_path, std::string prefix)
    : inc_path_(std::move(inc_path)), prefix_(std::move(prefix)) {}

void FixtureWriter::Add(const CapturedCase& c) {
  if (c.skipped || c.body_words.empty()) {
    CapturedCase s = c;
    if (s.skip_reason.empty()) {
      s.skip_reason = c.body_words.empty() ? "no RUN()/empty body" : "skipped";
    }
    skipped_.push_back(std::move(s));
    return;
  }
  included_.push_back(c);
}

int FixtureWriter::Finish() {
  // Drop absolute targets whose expected value is a host address (it lands in
  // this case's code buffer): ADR/ADRP/label/LR values do not survive
  // relocation to gaby's load address. The differential oracle still covers the
  // case. (Most address-producing bodies are already skipped wholesale by the
  // load/store + PC-rel filter; this catches the residue, e.g.
  // branch-to-label.)
  for (CapturedCase& c : included_) {
    std::vector<AssertTarget> kept;
    for (const AssertTarget& a : c.asserts) {
      const bool is_addr = c.code_hi > c.code_lo &&
                           a.expected_lo >= c.code_lo &&
                           a.expected_lo < c.code_hi;
      if (is_addr) {
        c.address_asserts += 1;
      } else {
        kept.push_back(a);
      }
    }
    c.asserts = std::move(kept);
  }

  std::ofstream inc(inc_path_);
  if (!inc) {
    std::fprintf(stderr, "fixture_writer: cannot open %s\n", inc_path_.c_str());
    return -1;
  }

  inc << "// Copyright 2026, the gaby-vm authors\n"
      << "// SPDX-License-Identifier: BSD-3-Clause\n"
      << "//\n"
      << "// GENERATED by tools/vixl_test_extract — DO NOT EDIT BY HAND.\n"
      << "// Regenerate with -DGABY_VM_BUILD_VIXL_EXTRACT=ON + "
         "-DVIXL_SRC_DIR.\n"
      << "// See docs/testing.md and the sibling manifest for "
         "inclusions/drops.\n"
      << "#include \"vixl_port_fixture.h\"\n\n"
      << "namespace gaby_vm::vixl_port {\n"
      << "namespace {\n\n";

  // Shared canonical entry (VIXL post-ResetState). Verified uniform below; any
  // outlier gets its own factory so correctness never depends on the
  // assumption.
  const bool have_cases = !included_.empty();
  if (have_cases) {
    inc << "RegisterFile Make" << prefix_ << "Entry() {\n";
    EmitEntryBody(inc, included_.front().entry);
    inc << "}\n\n";
  }

  std::vector<std::string> entry_refs;  // per-case entry expression
  for (size_t i = 0; i < included_.size(); ++i) {
    const CapturedCase& c = included_[i];
    if (EntryEqual(c.entry, included_.front().entry)) {
      entry_refs.push_back("shared_entry");
    } else {
      inc << "RegisterFile Make" << prefix_ << "_" << i << "_entry() {\n";
      EmitEntryBody(inc, c.entry);
      inc << "}\n\n";
      std::ostringstream ref;
      ref << "Make" << prefix_ << "_" << i << "_entry()";
      entry_refs.push_back(ref.str());
    }

    inc << "constexpr uint32_t " << prefix_ << "_" << i << "_code[] = {";
    for (size_t w = 0; w < c.body_words.size(); ++w) {
      if (w) {
        inc << ", ";
      }
      inc << "0x" << std::hex << c.body_words[w] << std::dec << "u";
    }
    inc << "};\n";

    if (!c.asserts.empty()) {
      inc << "constexpr AssertTarget " << prefix_ << "_" << i
          << "_asserts[] = {\n";
      for (const AssertTarget& a : c.asserts) {
        inc << "    {" << KindName(a.kind) << ", " << unsigned{a.reg} << ", "
            << Hex(a.expected_lo) << ", " << Hex(a.expected_hi) << "},\n";
      }
      inc << "};\n";
    }
    inc << "\n";
  }

  inc << "}  // namespace\n\n"
      << "inline const PortedFixture* " << prefix_
      << "Fixtures(size_t* count) {\n";
  if (have_cases) {
    inc << "  static const RegisterFile shared_entry = Make" << prefix_
        << "Entry();\n";
  }
  inc << "  static const PortedFixture fixtures[] = {\n";
  for (size_t i = 0; i < included_.size(); ++i) {
    const CapturedCase& c = included_[i];
    inc << "      {\"" << c.name << "\", " << prefix_ << "_" << i << "_code, "
        << c.body_words.size() << ", " << entry_refs[i] << ", ";
    if (c.asserts.empty()) {
      inc << "nullptr, 0},\n";
    } else {
      inc << prefix_ << "_" << i << "_asserts, " << c.asserts.size() << "},\n";
    }
  }
  inc << "  };\n"
      << "  *count = sizeof(fixtures) / sizeof(fixtures[0]);\n"
      << "  return fixtures;\n"
      << "}\n\n"
      << "}  // namespace gaby_vm::vixl_port\n";
  inc.close();

  // Manifest: manifest_<family>.md next to the .inc.
  std::string dir = inc_path_;
  auto slash = dir.find_last_of('/');
  dir = (slash == std::string::npos) ? std::string(".") : dir.substr(0, slash);
  std::string manifest_path = dir + "/manifest_" + Lower(prefix_) + ".md";
  std::ofstream man(manifest_path);
  if (man) {
    man << "# Ported VIXL cases — " << prefix_ << " family\n\n"
        << "Generated by `tools/vixl_test_extract`. DO NOT EDIT BY HAND.\n\n"
        << "- Included: **" << included_.size() << "**\n"
        << "- Skipped:  **" << skipped_.size() << "**\n\n"
        << "## Included\n\n";
    for (size_t i = 0; i < included_.size(); ++i) {
      const CapturedCase& c = included_[i];
      man << "- `" << c.name << "` — " << c.body_words.size() << " body words, "
          << c.asserts.size() << " assert target(s)";
      if (c.dropped_asserts) {
        man << ", " << c.dropped_asserts << " non-replayable assert(s) dropped";
      }
      if (!c.required_features.empty() &&
          c.required_features != "CPUFeatures{ }") {
        man << " — features: " << c.required_features;
      }
      man << "\n";
    }
    man << "\n## Skipped\n\n";
    for (const CapturedCase& c : skipped_) {
      man << "- `" << c.name << "` — " << c.skip_reason << "\n";
    }
  } else {
    std::fprintf(stderr,
                 "fixture_writer: cannot open %s\n",
                 manifest_path.c_str());
  }

  std::printf("%s: wrote %zu included, %zu skipped -> %s\n",
              prefix_.c_str(),
              included_.size(),
              skipped_.size(),
              inc_path_.c_str());
  return static_cast<int>(included_.size());
}

}  // namespace gaby_vm::extract
